config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/update'
  devise_for :users, controllers: {registrations: "registrations"}
  root to: 'pages#home'

  get "profile", to: "pages#profile", as: :profile
  get "stats", to: "entries#my_stats", as: :my_stats
  get "race-dashboard", to: "races#race_dashboard", as: :race_dashboard
  put "update-balance", to: "races#update_balance", as: :update_balance
  get "claim-bets", to: "bets#claim_bets", as: :claim_bets
  get "game", to: "pages#game", as: :game

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries, only: [:index, :show, :new, :create, :destroy]
  resources :habits, only: [:new, :create]
  resources :races, shallow: true do
    resources :bets
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user

  FEELINGS = ['stressed', 'lonely', 'happy', 'bored', 'excited', 'down', 'angry', 'anxious']
  CONTEXT = ["I've just had an argument", "I've just finished eating", "I'm drinking a glass of alcohol", "I want to relax",
             "I'm at a concert", "I'm going to go to bed", "I'm taking a break", "I'm in a car", "I'm drinking a cup of coffee",
             "I'm at the phone", "I've made love", "I'm drinking a cup of tea", "I'm watching television", "I've just woken up",
             "I'm working", "I'm in a bar", "I'm celebrating something", "I'm partying", "I'm with smokers", "I want to keep my hands busy", "I'm restless", "I'm missing the smell of cigarettes", "I'm missing the taste of cigarettes", "I'm touching an object related to tobacco", "I'm taking a walk", "I'm hungry", "Nothing special", "Other"]

  validates :craving, numericality: { only_integer: true }, presence: true, inclusion: (0..100)
  validates :date, presence: true
  validates :feeling, presence: true, inclusion: FEELINGS
  validates :cig_smoked, presence: true, numericality: { only_integer: true, greater_then_or_equal_to: 0 }
  validates :context, presence: true, inclusion: CONTEXT
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :find_entry, only: [:show, :destroy]

  def index
    @entries = policy_scope(Entry).order(date: :desc)
  end

  def show
  end

  def new
    @entry = Entry.new
    authorize @entry
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user
    authorize @entry
    if @entry.save
      redirect_to entries_path
    else
      render :new
    end
  end

  def destroy
    @entry.destroy

    redirect_to entries_path
  end

  def my_stats
    @cig_entries = Entry.where('cig_smoked > 0 AND user_id = ?', current_user.id).order(date: :asc)
    @date_cigs = reduce_same_date_entries(@cig_entries)

    @entries = Entry.all
    @feelings = get_feelings(@entries)
    @context  = get_context(@entries)

    @feelings_count = get_count(@feelings)
    @context_count = get_count(@context)

    authorize @cig_entries
  end

  private

  def find_entry
    @entry = Entry.find(params[:id])
    authorize @entry
  end

  def entry_params
    params.require(:entry).permit(:date, :feeling, :craving, :cig_smoked, :context)
  end

  # def reduce_same_date_entries(entries)
  #   date_cig = []
  #   entries.each do |entry|
  #     dates = date_cig.map { |ary| ary[0] }
  #     if date_cig.empty? || !dates.include?(entry.date.to_s)
  #       cig_entry = [
  #         entry.date.to_s,
  #         entry.cig_smoked
  #       ]
  #       date_cig << cig_entry
  #     else
  #       existing_date = date_cig.select { |ary| ary[0] == entry.date.to_s }
  #       existing_date[0][1] += entry.cig_smoked
  #     end
  #   end
  #   date_cig
  # end

  def get_feelings(entries)
    entries.map { |entry| entry.feeling }
  end

  def get_context(entries)
    entries.map { |entry| entry.context }
  end

  def get_count(array)
    counts = Hash.new(0)
    array.each { |elem| counts[elem] += 1 }
    sorted_counts = counts.sort_by { |k, v| -v }
    sorted_counts.first(5).to_h
  end
end

app/views/entries/index.html.erb
<div class="diary">
  <div class="title">
    <p id="back"><%= link_to "Back", profile_path %></p>
    <h1 id="diary">Diary</h1>
  </div>
  <div class="entries">
    <% if @entries.empty? %>
      <p>No entries logged yet!</p>
    <% else %>
      <% @entries.each do |entry| %>
        <%= link_to entry_path(entry) do %>
          <div class="entry-card">
            <div class="text">
              <% if entry.cig_smoked == 0 %>
                <div class="dot" style="border-color: #00a67a"></div>
                <p class="date"><%= entry.date %></p>
                <h5 class="craving-title" style="color: #00a67a;">Craving overcome</h5>
              <% else %>
                <div class="dot" style="border-color: #0096DE;"></div>
                <p class="date"><%= entry.date %></p>
                <h5 class="smoked-title" style="color: #0096DE;">Smoked cigarette</h5>
              <% end %>
            </div>
            <div class="arrow">
              <i class="fas fa-chevron-right"></i>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/entries/my_stats.html.erb
<div class='container'>
  <div class="stats-title">
    <h1>My Stats</h1>
    <p id="back"><%= link_to "Back", profile_path %></p>
  </div>
  <div class="charts">
    <div class="cigarettes-chart">
      <canvas id="cigChart" width="80%" height="50%" data-cigs="<%= @date_cigs %>"></canvas>
    </div>

    <div class="cigarettes-chart">
      <canvas id="feelingsChart" width="80%" height="50%" data-feelings="<%= @feelings_count.to_json %>"></canvas>
    </div>

    <div class="cigarettes-chart">
      <canvas id="contextChart" width="80%" height="50%" data-context="<%= @context_count.to_json %>"></canvas>
    </div>
  </div>

  <%= javascript_pack_tag 'cigs-chart' %>
  <%= javascript_pack_tag 'context-chart' %>
  <%= javascript_pack_tag 'feelings-chart' %>
</div>

app/views/entries/new.html.erb
<div class="diary">
  <p id="back"><%= link_to "Back", profile_path %></p>
  <div class="title">
    <h1>Create a new entry</h1>
    <p>If you feel like smoking or have smoked recently, take a moment to fill in a few details about how you felt.</p>
  </div>
  <div class="form">
    <%= simple_form_for @entry do |f| %>
      <%= f.input :date, label: "When did it happen?", input_html: { id: "date" } %>
      <%= f.input :cig_smoked, as: :integer, label: "How many did you smoke?", input_html: { id: "cig-smoked", value: 0 }, wrapper_html: { id: "cigarettes-smoked" } %>
      <%= f.input :craving, as: :range, min_max: true, input_html: { min: 0, max: 10, step: 10 }, label: "How strong is your craving from 0 to 10?", input_html: { id: "craving" } %>
      <%= f.input :feeling, collection: Entry::FEELINGS, label: "How did you feel?", input_html: { id: "feeling" } %>
      <%= f.input :context, collection: Entry::CONTEXT, label: "Context:", input_html: { id: "context" } %>
      <%= f.submit "Next", class: "btn next" %>
    <% end %>
  </div>
</div>

app/views/entries/show.html.erb
<div class="diary">
  <div class="nav">
    <p id="delete" >
      <%= link_to "Delete",
              entry_path(@entry),
              method: :delete,
              data: { confirm: "Are you sure?" }
              %>
    </p>
    <p id="back"><%= link_to "Back", entries_path %></p>
  </div>
  <div class="entry-show">
    <div id="entry-title" class="title">
      <% if @entry.cig_smoked.zero? %>
        <h1 class="overcome">I overcame a craving</h1>
      <% else %>
        <h1 class="smoked">I smoked</h1>
      <% end %>
      <p><%= @entry.date %></p>
    </div>
    <div class="entry-body">
      <div class="entry">
        <p>Feeling:</p>
        <p class="color-text"><%= @entry.feeling.capitalize %></p>
      </div>
      <div class="entry">
        <p>Context:</p>
        <p class="color-text"><%= @entry.context %></p>
      </div>
      <div class="entry">
        <p>Intensity:</p>
        <p class="color-text"><%= (@entry.craving / 10) %></p>
      </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'entry-show' %>