config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/update'
  devise_for :users, controllers: {registrations: "registrations"}
  root to: 'pages#home'

  get "profile", to: "pages#profile", as: :profile
  get "stats", to: "entries#my_stats", as: :my_stats
  get "race-dashboard", to: "races#race_dashboard", as: :race_dashboard
  put "update-balance", to: "races#update_balance", as: :update_balance
  get "claim-bets", to: "bets#claim_bets", as: :claim_bets
  get "game", to: "pages#game", as: :game

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries, only: [:index, :show, :new, :create, :destroy]
  resources :habits, only: [:new, :create]
  resources :races, shallow: true do
    resources :bets
  end
end

app/models/race.rb
class Race < ApplicationRecord
  has_one :win
  has_many :losses, dependent: :destroy
  has_many :lanes, dependent: :destroy
  has_many :users, through: :lanes
  has_many :bets, through: :lanes

  MONTHS = [nil, 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
    def index
        @races = policy_scope(Race).order(start_time: :asc).where('start_time > ?', Time.now).limit(10)
        authorize @races
    end

    def show
        @race = Race.find(params[:id])
        @racer = user_is_racer?(@race)
        @better = user_has_bets_on_race?(@race)
        @lanes = @race.lanes
        @average_cigs = []
        @ranking = []
        @pool = race_pool(@race)
        @race.lanes.each do |lane|
          lane_sum = lane_total(lane)
          odds = lane_sum == 0 ? '10/1' : (race_pool(@race) / lane_sum).to_r
          @ranking << { user: lane.user.username, total_cigs: cigs_since_race_began(lane) }
          @average_cigs << Hash[lane.user.username, {lane_total: lane_total(lane), odds: odds}]
      end
        @ranking.sort_by! { |k| k[:total_cigs]}
        authorize @race
    end

    def new
        @race = Race.new
        @max_date = Date.today + 1.week
        authorize @race
    end

    def create
        @race = Race.new(race_params)
        @race.end_time = race_params[:start_time].to_time + race_params[:duration].to_i.days
 
        p @race
        authorize @race
        if @race.save
            redirect_to race_path(@race)
        else
            render :new
        end
    end

    def update
        @race = Race.find(params[:id])

        authorize @race
        join_race(@race) if params[:join_race]
    end

    def destroy
        @race = Race.find(params[:id])
        @race.destroy
        if @race.destroy
            redirect_to profile_path
        else
        end
    end

    def race_dashboard
        @races = Race.includes(:bets)
        @my_bets = Bet.where('user_id = ? AND winnings_have_been_collected = ?', current_user.id, false)
        @unclaimed_winnings = []
        @my_bets.each do |bet|
            @unclaimed_winnings << bet if bet.race.end_time < Time.now
        end
        @bets = current_user.bets.order(created_at: :desc)
        @my_lanes = current_user.lanes.order(created_at: :desc)
        @balance = current_user.balance
        authorize @races
    end

    def update_balance
        p params
        @race = Race.first
        authorize @race
        current_user.update(balance: params[:earned_money].to_i + current_user.balance)
        if params[:bet_id]
            @bet = Bet.find(params[:bet_id])
            @bet.update(winnings_have_been_collected: true)
            puts "🪕🪕🪕🪕🪕🪕🪕🪕🪕🪕🪕🪕🪕"
            p @bet
        end
        puts current_user.balance
        puts "💰"

    end

    private

    def race_params
        params.require(:race).permit(:start_time, :duration)
    end

    def join_race(race)
        @lane = Lane.new
        @lane.user = current_user
        @lane.race = race
        @lane.save
    end

    def cigs_since_race_began(lane)
        cig_total = 0
        relevant_entries = lane.user.entries.where('date > ? AND date < ?', lane.race.start_time, lane.race.end_time)
        relevant_entries.each do |entry|
            cig_total += entry.cig_smoked
        end
        cig_total
    end

end

app/views/races/index.html.erb
<div class="race-index">
  <div class="race-nav">
    <%= link_to  "RACES", race_dashboard_path, class: 'race-nav-btn' %>
    <%= link_to  "PROFILE", profile_path, class: 'race-nav-btn' %>
  </div>
  <div class="race-index-top"></div>
  <div class="race-index-bottom"></div>
  <div class="race-index-info-holder">
    <div class="custom-container">
      <% @races.each do |race| %>
        <% unless user_is_racer?(race) || user_has_bets_on_race?(race) %>
          <div class="race-index-custom-card upcoming-card thick-border" >
            <div class="race-index-card-title">
              <%= name_race(race) %>
            </div>
            <div class="race-index-card-starttime">
              Start Time: <%= Race::MONTHS[race.start_time.month]%>, <%= race.start_time.day  %>
              <br>
              End Time: <%= Race::MONTHS[race.end_time.month]%>, <%= race.end_time.day  %>
            </div>
            <%= link_to  "Bet on this race", new_race_bet_path(race), class: "race-btn green" %>
            <% unless race_full?(race) %>
              <%= link_to  "Join this race", race_path(race), class: "race-btn blue" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_pack_tag "races-index" %>

app/views/races/new.html.erb
<div class="race-nav">
  <%= link_to  "RACES", race_dashboard_path, class: 'race-nav-btn' %>
  <%= link_to  "PROFILE", profile_path, class: 'race-nav-btn' %>
</div>
<div class="new-race-container">
  <div class="new-race-form-container thick-border">
    <%= simple_form_for @race do |f| %>
      <%= f.label :start_time, "RACE START DATE" %>
      <%= f.date_field :start_time, min: Date.today + 1.day, max: @max_date %>
      <br>
      <%= f.input :duration, label: "RACE DURATION IN DAYS", input_html: {min: 5, max: 30, value: 5} %>
      <%= f.submit "CREATE RACE", class: 'race-btn'%>
    <% end %>
  </div>
</div>

app/views/races/race_dashboard.html.erb
<div class="race-dashboard-container">
  <div class="uncollected-earnings">
    <% if @unclaimed_winnings.length > 0 %>
      <div class="uncollected-earnings-box">
        <div class="closer-btn">X</div>
        YOU HAVE UNCOLLECTED WINNINGS FROM BETS.
        <button class="race-btn" id="claim-money-btn">💰CLAIM MY MONEY💰</button>
      </div>
    </div>
  <% end %>
  <div class="dashboard-box">
    <div class="small-title">Nicotine Derby</div>
    <p id="balance">YOUR BALANCE: $<%= number_with_delimiter(@balance) %></p>
    <div class="dashboard-buttons">
      <button id="upcoming-race-btn" class="race-btn" value="upcomingRaces">UPCOMING</button>
      <button id="open-race-btn" class="race-btn" value="openRaces">OPEN</button>
      <button id="finished-race-btn" class="race-btn" value="completedRaces" >FINISHED</button>
    </div>
    <div class="upcoming-races" hidden>
      <div class="smaller-title">Upcoming Races</div>
      <div class="flex-direction-row center">
        <div class="flex-direction-column">
          <div class="box-column underline">Betting on</div>
          <div class="race-list">
            <% betting_on_upcoming = 0 %>
            <% @bets.each do |bet| %>
              <% if race_not_started?(bet.race) && betting_on_upcoming < 4 %>
                <% betting_on_upcoming += 1%>
                <%= link_to race_path(bet.race) do%>
                  <div class="race-list-item"><%= short_name(bet.race) %> </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="flex-direction-column">
          <div class="box-column underline">Racing in</div>
          <div class="race-list">
            <% racing_in_upcoming = 0 %>
            <% @my_lanes.each do |lane| %>
              <% if race_not_started?(lane.race) && racing_in_upcoming < 4 %>
                <% racing_in_upcoming += 1%>
                <%= link_to race_path(lane.race) do%>
                  <div class="race-list-item"><%= short_name(lane.race) %> </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class=""></div>
      </div>
    </div>
    <div class="open-races">
      <div class="smaller-title">Open Races</div>
      <div class="flex-direction-row center">
        <div class="flex-direction-column">
          <div class="box-column underline">Betting on</div>
          <div class="race-list">
            <% betting_on_open = 0 %>
            <% @bets.each do |bet| %>
              <% if race_ongoing?(bet.race) && betting_on_open < 4 %>
                <% betting_on_open += 1%>
                <%= link_to race_path(bet.race) do%>
                  <div class="race-list-item"><%= short_name(bet.race) %> </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="flex-direction-column">
          <div class="box-column underline">Racing in</div>
          <div class="race-list">
            <% racing_in_open = 0 %>
            <% @my_lanes.each do |lane| %>
              <% if race_ongoing?(lane.race) && racing_in_open < 4 %>
                <% racing_in_open += 1%>
                <%= link_to race_path(lane.race) do%>
                  <div class="race-list-item"><%= short_name(lane.race) %> </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class=""></div>
      </div>
    </div>
    <div class="completed-races" hidden >
      <div class="smaller-title">Finished Races</div>
      <div class="flex-direction-row center">
        <div class="flex-direction-column">
          <div class="box-column underline">Bet on</div>
          <div class="race-list">
            <% betting_on_completed = 0 %>
            <% @bets.each do |bet| %>
              <% if race_finished?(bet.race) && betting_on_completed < 4 %>
                <% betting_on_completed += 1%>
                <%= link_to race_path(bet.race) do%>
                  <div class="race-list-item"><%= short_name(bet.race) %> </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="flex-direction-column">
          <div class="box-column underline">Raced in</div>
          <div class="race-list">
            <% racing_in_completed = 0 %>
            <% @my_lanes.each do |lane| %>
              <% if race_finished?(lane.race) && racing_in_completed < 4%>
                <% racing_in_completed += 1 %>
                <%= link_to race_path(lane.race) do%>
                  <div class="race-list-item"><%= short_name(lane.race) %></div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class=""></div>
      </div>
    </div>
    <div class="menu-box ">
      <div class="smaller-title">Menu</div>
      <%= link_to  "FIND A NEW RACE", races_path, class: 'race-btn' %>
      <%= link_to  "CREATE A RACE", new_race_path, class: 'race-btn' %>
      <%= link_to  "GET MONEY", game_path, class: 'race-btn'%>
      <%= link_to  "PROFILE", profile_path, class: 'race-btn'%>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'race-dashboard' %>

app/views/races/show.html.erb
<div class="race-show-top"></div>
<div class="race-nav">
  <%= link_to  "RACES", race_dashboard_path, class: 'race-nav-btn' %>
  <%= link_to  "PROFILE", profile_path, class: 'race-nav-btn' %>
</div>
<div class="race-show-bottom"></div>
<div class="race-show">
  <div class="new-bet-racers-container">
    The Nicotine Derby
    <div class="new-bet-racers-info-container thick-border">
      <div class="new-bet-racer-column">
        <table>
          <tr>
            <td class="underline">RACER</td>
            <td class="underline">ODDS</td>
            <td class="underline">TOTAL BETS</td>
          </tr>
          <% @average_cigs.each do |average_cig| %>
            <% average_cig.each do |k, v|%>
              <tr>
                <td><% if k == current_user.username %>
                    ✨
                  <% end %>
                  <%=k%></td>
                <td><%= v[:odds] %></td>
                <td>$<%= number_with_delimiter(v[:lane_total]) %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
        <% if @better && !@racer %>
          <div class="my-bet-display">YOUR BET: $<%= @better.amount %> on <%= @better.lane.user.username %></div>
        <% end %>
      </div>
    </div>
  </div>
  <% if race_ongoing?(@race)%>
    <div class="new-bet-timer-container thick-border">
      <div class="timer-title">RACE ENDS IN</div>
      <div class="new-bet-timer"><%= (@race.end_time - Time.now).to_i %></div>
    </div>
  <% end %>
  <% if race_not_started?(@race) %>
    <div class="new-bet-timer-container thick-border">
      <div class="timer-title">RACE BEGINS IN</div>
      <div class="new-bet-timer"><%= (@race.start_time - Time.now).to_i %></div>
    </div>
  <% end %>
  <% unless race_not_started?(@race) %>
    <div class="race-ranking thick-border">
      <% if race_finished?(@race) %>
        <div class="smaller-title">FINAL RANKINGS</div>
      <% else %>
        <div class="smaller-title">CURRENT RANKINGS</div>
      <% end %>
      <% @ranking.each_with_index do |racer, index| %>
        <div class="individual-racer-data">
          <div><%= index + 1 %>: <%= racer[:user] %>
            <% if index == 0 %>
              🏆
            <% end %>
          </div>
          <div> <%= racer[:total_cigs] %> CIGARETTES</div>
        </div>
      <% end %>
    </div>
  <% end %>
  <% if race_not_started?(@race) %>
    <% unless @racer || @better %>
      <button id="race-join-btn" class="race-btn">JOIN THIS RACE</button>
    <% end %>
  <% end %>
</div>
<%= javascript_pack_tag "race-show" %>