config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/update'
  devise_for :users, controllers: {registrations: "registrations"}
  root to: 'pages#home'

  get "profile", to: "pages#profile", as: :profile
  get "stats", to: "entries#my_stats", as: :my_stats
  get "race-dashboard", to: "races#race_dashboard", as: :race_dashboard
  put "update-balance", to: "races#update_balance", as: :update_balance
  get "claim-bets", to: "bets#claim_bets", as: :claim_bets
  get "game", to: "pages#game", as: :game

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries, only: [:index, :show, :new, :create, :destroy]
  resources :habits, only: [:new, :create]
  resources :races, shallow: true do
    resources :bets
  end
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :user
  belongs_to :lane

  validates :amount, presence: true
  validates :lane_id, presence: true
  validates :user, presence: true

  has_one :race, through: :lane
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
    def index
        @bets = policy_scope(Bet).order(created_at: :desc).where(user: current_user)
    end

    def show
        @bet = Bet.find(params[:id])
    end

    def new
      @bet = Bet.new
      @race = Race.find(params[:race_id])
      @average_cigs = []
      @pool = race_pool(@race)
      @user = current_user
      @race.lanes.each do |lane|
        lane_sum = lane_total(lane)
        odds = lane_sum == 0 ? '10/1' : (race_pool(@race) / lane_sum).to_r
        @average_cigs << Hash[lane.user.username, {avg_cig: avg_cig(lane.user), odds: odds}]
      end
      authorize @bet
    end

    def create
      @bet = Bet.new(bet_params)
      @bet.user = current_user
      authorize @bet

      if @bet.save
        current_user.update(balance: @bet.user.balance - @bet.amount)
        redirect_to race_dashboard_path
      else
        render :new
      end
    end

    def edit
      @bet = Bet.find(params[:id])
    end

    def update
        @bet = Bet.find(bet_params)
    end

    def destroy
        @bet = Bet.find(bet_params)
        if @bet.destroy
        # redirect to somewhere
        else
        # render something
        end
    end

    def claim_bets
      @bets = Bet.where('user_id = ? AND winnings_have_been_collected = ?', current_user.id, false)
      @balance = current_user.balance
      authorize @bets
      @unclaimed_winnings = []
      @bets.each do |bet|
          @unclaimed_winnings << bet if bet.race.end_time < Time.now
      end
    end

    private

    def bet_params
        params.require(:bet).permit(:amount, :lane_id)
    end

end

app/views/bets/claim_bets.html.erb
<div class="race-nav">
  <%= link_to  "RACE DASHBOARD", race_dashboard_path, class: 'race-nav-btn' %>
  <%= link_to  "PROFILE", profile_path, class: 'race-nav-btn' %>
</div>
<div class="new-bet-top"></div>
<div class="new-bet-bottom"></div>
<div class="unclaimed-bets-page">
  <div class="unclaimed-bet-page-current-balance thick-border">💰CURRENT BALANCE: $<%= number_with_delimiter(@balance)  %>💰</div>
  <% @unclaimed_winnings.each do |bet| %>
    <div class="race-index-custom-card thick-border" data-bet-id="<%= bet.id %>">
      <div class="race-index-card-title">
        <%= name_race(bet.race) %>
      </div>
      <br>
      <div class="unclaimed-bets-winnings">WINNINGS: $<%= number_with_delimiter((race_pool(bet.race) / lane_total(bet.lane)) * bet.amount) %></div>
      <%= link_to  "RACE RESULTS", race_path(bet.race), class: 'race-btn' %>
      <button class="race-btn claim-bet-btn" data-bet-id="<%= bet.id %>" value="<%=(race_pool(bet.race) / lane_total(bet.lane)) * bet.amount%>">ADD TO MY BALANCE</button>
    </div>
  <% end %>
</div>
<div class="original-balance" data-balance="<%= @balance %>" hidden></div>
<%= javascript_pack_tag 'claim-bets' %>

app/views/bets/edit.html.erb
<h1>This is where a user can edit a bet that they have made</h1>

app/views/bets/index.html.erb
<h1>These are your bets</h1>
<div class="custom-container">
  <% @bets.each do |bet|%>
    <div class="custom-card">
      <%= name_race(bet.lane.race) %>
      <div class="bets-index-card-details">
        <div>Amount: $<%= bet.amount %></div>
        <div>Start Time: <%= Race::MONTHS[bet.race.start_time.month]%>, <%= bet.race.start_time.day %></div>
        <div>End Time: <%= Race::MONTHS[bet.race.end_time.month]%>, <%= bet.race.end_time.day %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/bets/new.html.erb
<div class="new-bet">
  <div class="new-bet-top"></div>
  <div class="new-bet-bottom"></div>
  <div class="race-nav">
    <%= link_to  "RACES", race_dashboard_path, class: 'race-nav-btn' %>
    <%= link_to  "PROFILE", profile_path, class: 'race-nav-btn' %>
  </div>
  <div class="stuff-container">
    <%= simple_form_for [@race, @bet] do |f| %>
      <div class="new-bet-racers-container">
        The Nicotine Derby
        <div class="new-bet-racers-info-container thick-border">
          <div class="new-bet-racer-column">
            <div class="column-title">Racer</div>
            <%= f.input :lane_id, label: "Choose a racer", collection: @race.lanes.map {|lane| [lane.user.username, lane.id]}, as: :radio_buttons %>
          </div>
          <div class="new-bet-stats-column">
            <div class="column-title">Stats</div>
          </div>
        </div>
      </div>
      <div class="new-bet-timer-container thick-border">
        <div class="timer-title">RACE BEGINS IN</div>
        <div class="new-bet-timer"><%= (@race.start_time - Time.now).to_i %></div>
      </div>
      <div class="bet-placer thick-border">
        <div class="current-pool">Your balanace: $<%= number_with_delimiter(@user.balance)  %></div>
        <div class="current-pool">Current pool: $<%= number_with_delimiter(@pool) %></div>
        <div style="display: flex;"><%= image_tag 'dollar.png', height: 40, width: 29 %><%= f.input :amount, label: false, input_html: {min: 10, max: 1000, value: 10, step: 10} %></div>
        <%= f.submit "Bet", class: 'race-btn'%>
      </div>
    <% end %>
    <div class="hidden-info" data-hidden-info="<%=@average_cigs.to_json %>" hidden></div>
    <div class="user-balance" data-balance="<%= @user.balance %>" hidden></div>
  </div>
</div>
<%= javascript_pack_tag 'new-bets' %>