config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/update'
  devise_for :users, controllers: {registrations: "registrations"}
  root to: 'pages#home'

  get "profile", to: "pages#profile", as: :profile
  get "stats", to: "entries#my_stats", as: :my_stats
  get "race-dashboard", to: "races#race_dashboard", as: :race_dashboard
  put "update-balance", to: "races#update_balance", as: :update_balance
  get "claim-bets", to: "bets#claim_bets", as: :claim_bets
  get "game", to: "pages#game", as: :game

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  resources :entries, only: [:index, :show, :new, :create, :destroy]
  resources :habits, only: [:new, :create]
  resources :races, shallow: true do
    resources :bets
  end
end

app/views/pages/game.html.erb
<div class="new-race-top"></div>
<div class="new-race-bottom"></div>
<div class="race-nav">
  <%= link_to  "RACE DASHBOARD", race_dashboard_path, class: 'race-nav-btn' %>
  <%= link_to  "PROFILE", profile_path, class: 'race-nav-btn' %>
</div>
<div class="game">
  <div class="game-instructions thick-border">
    <div class="game-stats">
      <div class="game-current-balance">YOUR BALANCE: $<%= number_with_delimiter(@balance) %></div>
      <div class="game-time">TIME: 0:00</div>
      <div class="money-earned">CASH EARNED: $0</div>
    </div>
  </div>
  <canvas id="game-canvas">
  </canvas>
  <button id="game-btn">JUMP</button>
  <div class="game-over-screen" hidden>
    <div class="you-lost-box">
      <div class="game-message"></div>
      <button id="race-dashboard-btn" class="race-btn">RACE DASHBOARD</button>
      <button id="profile-btn" class="race-btn">PROFILE </button>
      <button id="play-again-btn" class="race-btn">PLAY AGAIN?</button>
    </div>
  </div>
</div>
<div class="money-flash">
  <div class="money-flash-text" hidden>$500!</div>
</div>
<%= javascript_pack_tag 'game' %>

app/views/pages/home.html.erb
<div class="landing-container">
  <div class="banner">
    <div class="cover-sheet">
      <div class="title">
        <h1>Nicotine Derby</h1>
        <p>Race to Reduce Smoking</p>

        <%= link_to new_user_session_path do %>
          <button>Login</button>
        <% end %>

      </div>
      <div class="down-arrow">
        <span class="iconify" data-icon="bi:arrow-down-circle" data-inline="false"></span>
      </div>
    </div>
  </div>

  <div class="about-app">
    <div class="demo">
      <h2 id="how-it-works">How it Works</h2>
      <div class="info info-smoke">
        <div class="icons">
          <span class="iconify" data-icon="cil:smoke-free" data-inline="false"></span>
        </div>
        <p>Input How Much You Smoke</p>
      </div>
      <div class="info info-progress">
        <p id="track-text">Keep Track of Your Progress</p>
        <div class="icons">
          <span class="iconify" data-icon="carbon:chart-evaluation" data-inline="false"></span>
        </div>
      </div>
      <div class="info info-compete">
        <div class="icons">
          <span class="iconify" data-icon="emojione-monotone:horse" data-inline="false"></span>
        </div>
        <p>Compete and Win Cash</p>
      </div>
    </div>
  </div>

  <div class="developers-container">

    <div class="developers">
      <h4>Meet Our Developers</h4>
      <div class="select-one">
        <p>Select to See Their Profiles</p>
        <span class="iconify git-icon" data-icon="akar-icons:github-fill" data-inline="false"></span>
      </div>
    </div>

    <div class="git-profiles">
      <%= link_to "https://github.com/OoKiaoO", class: "git-links" do %>
        <div class="avatar" id="OoKiaoO"></div>
        <p class="names">Chiara Campalani</p>
      <% end %>


      <%= link_to "https://github.com/HatAndBread", class: "git-links" do  %>
        <div class="avatar" id="HatAndBread"></div>
        <p class="names">Joshua Hume</p>
      <% end %>


      <%= link_to "https://github.com/Ryu4fly", class: "git-links" do %>
        <div class="avatar" id="Ryu4fly"></div>
        <p class="names">Ryugi Suguro</p>
      <% end %>
    </div>

    <div class="footer">
      <p class="sponsor">Sponsered with <span class="iconify" data-icon="ant-design:heart-outlined" data-inline="false"></span> from Le Wagon</p>
    </div>

  </div>

</div>

app/views/pages/profile.html.erb
<div class="main-container">
  <div class="upper-section">
    <div class="user-welcome">
      <div class="avatar-img">
        <%= image_tag "https://images.unsplash.com/photo-1593085512500-5d55148d6f0d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80", class: "avatar-large"%>
      </div>
      <div class="welcome-text">
        <h3>Welcome back <%= current_user.username.capitalize %></h3>
        <p>How are you feeling today?</p>
        <p class="new-entry"><%= link_to "Log a new entry", new_entry_path, id: 'new-entry' %></p>
      </div>
      <p>
        <%= link_to destroy_user_session_path, id:'logout' do %>
          <i class="fas fa-ellipsis-v"></i>
        <% end %>
      </p>
    </div>
  </div>
  <div class="middle-section">
    <div class="progress-dashboard responsive-position">
      <h3>Your progress dashboard</h3>
      <div class="progress-cards">
        <div class="progress-element">
          <div class="number">
            <p>$</p>
            <p><%= @counters[:total_money] %></p>
          </div>
          <p class="elem-text">Money Saved</p>
        </div>
        <div class="progress-element">
          <div id="cigs-color" class="number">
            <p><%= @counters[:total_cigs] %></p>
          </div>
          <p class="elem-text">Cigarettes Not Smoked</p>
        </div>
        <div class="progress-element">
          <div id="balance-color" class="number">
            <p>$<%= @user_balance %></p>
          </div>
          <p class="elem-text">Races Balance</p>
        </div>
      </div>
    </div>
    <div class="link-cards">
      <%= link_to entries_path, id: 'diary-link', class: "link-card" do %>
        <div class="svg-container">
          <span class="iconify" data-inline="false" data-icon="fluent:book-star-24-regular" style="color: #fff;"></span>
        </div>
        <h5>Diary</h5>
        <p>Find and review all your entries here</p>
      <% end %>
      <%= link_to my_stats_path, id: 'stats', class: "link-card" do %>
        <div class="svg-container">
          <span class="iconify" data-inline="false" data-icon="zondicons:chart-bar" style="color: #fff;"></span>
        </div>
        <h5>My Stats</h5>
        <p>See the progress of your journey to quit smoking</p>
      <% end %>
    </div>
    <div class="timer">
      <div class="gradient-background outer-ring">
      </div>
      <div class="black-outer-circle">
        <div class="black-inner-circle">
          <h5>You quit smoking for</h5>
          <div class="timer-count">
            <div class="unit">
              <p class="number">2</p>
              <p>days<p>
            </div>
            <div class="unit">
              <p class="number">15</p>
              <p>hours<p>
            </div>
            <div class="unit">
              <p class="number">37</p>
              <p>minutes</p>
            </div>
          </div>
          <h5>Keep it up!</h5>
        </div>
      </div>
    </div>
  </div>
  <div class="wave-top">
    <div class="inner-wave-top"></div>
  </div>
  <div class="bottom-section">
      <div class="derby">
        <h3>The Nicotine Derby</h3>
        <p>Aim to reduce the amount you smoke, race against others and win the Nicotine Derby!<br>Not a smoker? Encourage the users participating by betting on them and follow their progress throughout the race!</p>
        <p id="races-b"><%= link_to "Go to the races!", race_dashboard_path, id: "races-button" %></p>
      </div>
  </div>
</div>